//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankita_TB
    {
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_City { get; set; }
    }
}
